#!/usr/bin/env python3
"""Create a Plan.md file using PlannerService."""

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path


def get_vault_path() -> Path:
    """Get vault path from environment or default."""
    vault = os.environ.get("VAULT_PATH", "~/AI_Employee_Vault")
    return Path(vault).expanduser()


def create_plan_via_service(
    task: str,
    objective: str,
    steps: list[str] | None,
    vault: Path
) -> dict:
    """Create a plan using PlannerService."""
    try:
        from ai_employee.config import VaultConfig
        from ai_employee.services.planner import PlannerService

        config = VaultConfig(root=vault)
        service = PlannerService(config)

        # Convert steps to dict format
        step_dicts = None
        if steps:
            step_dicts = [{"description": s} for s in steps]

        plan = service.create_plan(
            task=task,
            objective=objective,
            steps=step_dicts,
        )

        return {
            "success": True,
            "plan_id": plan.id,
            "task": task,
            "objective": plan.objective,
            "step_count": len(plan.steps),
            "status": plan.status.value,
        }

    except ImportError:
        return create_plan_standalone(task, objective, steps, vault)
    except Exception as e:
        return {"success": False, "error": str(e)}


def create_plan_standalone(
    task: str,
    objective: str,
    steps: list[str] | None,
    vault: Path
) -> dict:
    """Create a plan file (standalone mode)."""
    plans_dir = vault / "Plans"
    plans_dir.mkdir(parents=True, exist_ok=True)

    now = datetime.now()
    plan_id = f"plan_{now.strftime('%Y%m%d_%H%M%S')}"

    # Default steps if none provided
    if not steps:
        steps = [
            "Analyze requirements",
            "Design solution",
            "Implement changes",
            "Test implementation",
            "Document results",
        ]

    # Build steps markdown
    steps_md = ""
    for i, step in enumerate(steps, 1):
        steps_md += f"\n### Step {i}: {step}\n\n- **Status**: Pending\n- **Notes**: \n"

    content = f"""---
id: "{plan_id}"
task: "{task}"
objective: "{objective}"
status: "draft"
created_at: "{now.isoformat()}"
step_count: {len(steps)}
---

# Plan: {task}

**Objective**: {objective}

**Status**: Draft
**Created**: {now.strftime("%Y-%m-%d %H:%M")}

## Steps
{steps_md}
## Progress

| Step | Description | Status | Notes |
|------|-------------|--------|-------|
{chr(10).join(f'| {i} | {s} | Pending | - |' for i, s in enumerate(steps, 1))}

---
*Generated by AI Employee*
"""

    plan_file = plans_dir / f"{plan_id}.md"
    plan_file.write_text(content)

    return {
        "success": True,
        "plan_id": plan_id,
        "task": task,
        "objective": objective,
        "step_count": len(steps),
        "file": str(plan_file),
        "mode": "standalone",
    }


def main():
    parser = argparse.ArgumentParser(description="Create a Plan.md file")
    parser.add_argument("task", help="Task description")
    parser.add_argument("--objective", "-o", help="Plan objective", default="")
    parser.add_argument("--steps", "-s", nargs="+", help="Plan steps")
    parser.add_argument("--vault", help="Vault path override")
    parser.add_argument("--json", action="store_true", help="Output JSON")
    parser.add_argument("--standalone", action="store_true", help="Use standalone mode")

    args = parser.parse_args()
    vault = Path(args.vault).expanduser() if args.vault else get_vault_path()

    objective = args.objective or f"Complete: {args.task}"

    if args.standalone:
        result = create_plan_standalone(args.task, objective, args.steps, vault)
    else:
        result = create_plan_via_service(args.task, objective, args.steps, vault)

    if args.json:
        print(json.dumps(result, indent=2))
    else:
        if result["success"]:
            print(f"Plan created: {result['plan_id']}")
            print(f"   Task: {result['task']}")
            print(f"   Objective: {result['objective']}")
            print(f"   Steps: {result['step_count']}")
            if result.get("file"):
                print(f"   File: {result['file']}")
        else:
            print(f"Error: {result['error']}", file=sys.stderr)
            sys.exit(1)


if __name__ == "__main__":
    main()
