#!/bin/bash
# Initialize AI Employee Vault structure
# Usage: ./scripts/init_vault.sh [VAULT_PATH]

set -e

VAULT_PATH="${1:-$HOME/AI_Employee_Vault}"

echo "Initializing AI Employee Vault at: $VAULT_PATH"

# Create Bronze tier directories
mkdir -p "$VAULT_PATH/Inbox"
mkdir -p "$VAULT_PATH/Needs_Action/Email"
mkdir -p "$VAULT_PATH/Done"
mkdir -p "$VAULT_PATH/Drop"
mkdir -p "$VAULT_PATH/Quarantine"
mkdir -p "$VAULT_PATH/Logs"

# Create Silver tier directories
mkdir -p "$VAULT_PATH/Pending_Approval"
mkdir -p "$VAULT_PATH/Approved"
mkdir -p "$VAULT_PATH/Rejected"
mkdir -p "$VAULT_PATH/Plans"
mkdir -p "$VAULT_PATH/Needs_Action/WhatsApp"
mkdir -p "$VAULT_PATH/Needs_Action/LinkedIn"
mkdir -p "$VAULT_PATH/Social/LinkedIn/posts"
mkdir -p "$VAULT_PATH/Briefings"
mkdir -p "$VAULT_PATH/Schedules"

# Create Dashboard.md if not exists
if [ ! -f "$VAULT_PATH/Dashboard.md" ]; then
    cat > "$VAULT_PATH/Dashboard.md" << 'EOF'
# AI Employee Dashboard

**Last Updated**: Never

## Status

- **Watcher**: Not started
- **Pending Items**: 0
- **Processed Today**: 0

## Approval Queue

- **Pending Approvals**: 0
- **Approved Today**: 0
- **Rejected Today**: 0

## Active Plans

No active plans.

## Recent Activity

| Time | Action | Item | Result |
|------|--------|------|--------|
| - | - | - | - |

## Warnings

None

---
*Auto-generated by AI Employee*
EOF
    echo "Created Dashboard.md"
fi

# Create Company_Handbook.md if not exists
if [ ! -f "$VAULT_PATH/Company_Handbook.md" ]; then
    cat > "$VAULT_PATH/Company_Handbook.md" << 'EOF'
# Company Handbook

This handbook defines the rules and guidelines that govern how your AI Employee processes items. Edit these rules to customize the AI's behavior to match your preferences.

## Rules

### Rule 1: Priority Keywords
When processing items, check for these keywords and set priority:
- "urgent", "asap", "emergency" → priority: urgent
- "important", "priority" → priority: high
- "low priority", "when you can" → priority: low

### Rule 2: Large File Handling
Files larger than 10MB should be flagged for manual review and moved to Quarantine with a note.

### Rule 3: Default Behavior
Process all items in order received (FIFO - First In, First Out). Log all actions to the activity log.

### Rule 4: Email Handling
When processing emails:
- Summarize the key points
- Identify any action items requested
- Note the sender and date
- Flag if response is needed

### Rule 5: File Type Processing
- **Text files (.txt, .md)**: Extract content for processing
- **PDFs (.pdf)**: Note filename and metadata only
- **Images (.png, .jpg)**: Note filename and size
- **Data files (.csv, .json)**: Note structure and row/key count

### Rule 6: Error Recovery
If an error occurs during processing:
- Log the error with details
- Move the item to Quarantine
- Continue processing remaining items
- Report errors in the Dashboard warnings section

### Rule 7: Approval Workflow (Silver Tier)
Sensitive actions require human approval before execution:
- **Email sending**: All outbound emails need approval
- **Social posts**: LinkedIn posts need approval before publishing
- **Payments**: Any financial transactions need approval
Move items to /Pending_Approval/ and wait for user to move to /Approved/ or /Rejected/

### Rule 8: WhatsApp Monitoring (Silver Tier)
Monitor WhatsApp for keywords indicating urgent business needs:
- "urgent", "asap", "invoice", "payment", "help", "pricing"
Create action items in /Needs_Action/WhatsApp/ for messages matching keywords

### Rule 9: LinkedIn Engagement (Silver Tier)
Monitor LinkedIn engagement for business opportunities:
- Keywords: "interested", "pricing", "demo", "contact", "inquiry"
Create action items in /Needs_Action/LinkedIn/ for high-priority engagement

## Contact Information

**Owner**: [Your Name]
**Email**: [Your Email]
**Last Updated**: [Date]

## Notes

- Rules are applied in order (Rule 1 takes precedence over Rule 2, etc.)
- Add new rules by creating ### Rule N: sections
- The AI will re-read this handbook before each processing session
EOF
    echo "Created Company_Handbook.md"
fi

echo ""
echo "Vault initialized successfully!"
echo ""
echo "Bronze Tier Folders:"
echo "  - Inbox/"
echo "  - Needs_Action/Email/"
echo "  - Done/"
echo "  - Drop/"
echo "  - Quarantine/"
echo "  - Logs/"
echo ""
echo "Silver Tier Folders:"
echo "  - Pending_Approval/"
echo "  - Approved/"
echo "  - Rejected/"
echo "  - Plans/"
echo "  - Needs_Action/WhatsApp/"
echo "  - Needs_Action/LinkedIn/"
echo "  - Social/LinkedIn/posts/"
echo "  - Briefings/"
echo "  - Schedules/"
echo ""
echo "Created files:"
echo "  - Dashboard.md"
echo "  - Company_Handbook.md"
echo ""
echo "Next steps:"
echo "  1. Open $VAULT_PATH in Obsidian"
echo "  2. Start the watcher: uv run ai-employee watch --vault $VAULT_PATH"
echo "  3. Drop files into $VAULT_PATH/Drop/ to test"
echo "  4. Use skills: /post-linkedin, /send-email, /create-plan, /approve-action, /schedule-task"
