"""CLI entry point for AI Employee commands."""

import argparse
import sys
from pathlib import Path


def cmd_watch(args: argparse.Namespace) -> int:
    """Run the file system watcher command.

    Args:
        args: Parsed command line arguments

    Returns:
        Exit code (0 for success)
    """
    from ai_employee.watchers.filesystem import run_watcher

    vault_path = Path(args.vault).expanduser().resolve()

    if not vault_path.exists():
        print(f"Error: Vault path does not exist: {vault_path}")
        print("Please create the vault first or specify a valid path.")
        return 1

    print("Starting AI Employee File Watcher")
    print(f"Vault: {vault_path}")
    print(f"Watching: {vault_path / 'Drop'}")
    print("Press Ctrl+C to stop.\n")

    run_watcher(vault_path, interval=args.interval)
    return 0


def cmd_dashboard(args: argparse.Namespace) -> int:
    """Update the dashboard command.

    Args:
        args: Parsed command line arguments

    Returns:
        Exit code (0 for success)
    """
    from ai_employee.config import VaultConfig
    from ai_employee.services.dashboard import DashboardService

    vault_path = Path(args.vault).expanduser().resolve()

    if not vault_path.exists():
        print(f"Error: Vault path does not exist: {vault_path}")
        return 1

    config = VaultConfig(root=vault_path)
    service = DashboardService(config)

    service.update_dashboard()
    print(f"Dashboard updated: {config.dashboard}")
    return 0


def cmd_gmail_watch(args: argparse.Namespace) -> int:
    """Run the Gmail watcher command.

    Args:
        args: Parsed command line arguments

    Returns:
        Exit code (0 for success)
    """
    from ai_employee.watchers.gmail import run_gmail_watcher

    vault_path = Path(args.vault).expanduser().resolve()

    if not vault_path.exists():
        print(f"Error: Vault path does not exist: {vault_path}")
        print("Please create the vault first or specify a valid path.")
        return 1

    credentials_path = None
    if args.credentials:
        credentials_path = Path(args.credentials).expanduser().resolve()
        if not credentials_path.exists():
            print(f"Error: Credentials file not found: {credentials_path}")
            return 1

    print("Starting AI Employee Gmail Watcher")
    print(f"Vault: {vault_path}")
    print(f"Poll interval: {args.interval} seconds")
    print("Press Ctrl+C to stop.\n")

    run_gmail_watcher(vault_path, credentials_path, args.interval)
    return 0


def cmd_init(args: argparse.Namespace) -> int:
    """Initialize the vault structure command.

    Args:
        args: Parsed command line arguments

    Returns:
        Exit code (0 for success)
    """
    from ai_employee.config import VaultConfig

    vault_path = Path(args.vault).expanduser().resolve()

    config = VaultConfig(root=vault_path)
    config.ensure_structure()

    # Create initial Dashboard.md
    initial_dashboard = """# AI Employee Dashboard

**Last Updated**: Never

## Status

- **Watcher**: Not started
- **Pending Items**: 0
- **Processed Today**: 0

## Recent Activity

| Time | Action | Item | Result |
|------|--------|------|--------|
| - | - | - | - |

## Warnings

None

---
*Auto-generated by AI Employee*
"""

    if not config.dashboard.exists():
        config.dashboard.write_text(initial_dashboard)

    # Create initial Company_Handbook.md
    initial_handbook = """# Company Handbook

## Rules

### Rule 1: Priority Keywords
When processing items, check for these keywords and set priority:
- "urgent", "asap", "emergency" → priority: urgent
- "important", "priority" → priority: high

### Rule 2: Large File Handling
Files larger than 10MB should be flagged for manual review.

### Rule 3: Default Behavior
Process all items in order received (FIFO). Log all actions.

## Contact Information

Owner: [Your Name]
"""

    if not config.handbook.exists():
        config.handbook.write_text(initial_handbook)

    print(f"Vault initialized at: {vault_path}")
    print("Created folders:")
    print("  - Inbox/")
    print("  - Needs_Action/")
    print("  - Needs_Action/Email/")
    print("  - Done/")
    print("  - Drop/")
    print("  - Quarantine/")
    print("  - Logs/")
    print("Created files:")
    print("  - Dashboard.md")
    print("  - Company_Handbook.md")
    return 0


def create_parser() -> argparse.ArgumentParser:
    """Create the argument parser.

    Returns:
        Configured argument parser
    """
    parser = argparse.ArgumentParser(
        prog="ai-employee",
        description="Personal AI Employee - Autonomous Digital FTE",
    )

    parser.add_argument(
        "--version",
        action="version",
        version="%(prog)s 0.1.0",
    )

    subparsers = parser.add_subparsers(
        title="commands",
        dest="command",
        required=True,
    )

    # Watch command
    watch_parser = subparsers.add_parser(
        "watch",
        help="Start the file system watcher",
    )
    watch_parser.add_argument(
        "--vault",
        type=str,
        default="~/AI_Employee_Vault",
        help="Path to the Obsidian vault (default: ~/AI_Employee_Vault)",
    )
    watch_parser.add_argument(
        "--interval",
        type=int,
        default=60,
        help="Keep-alive interval in seconds (default: 60)",
    )
    watch_parser.set_defaults(func=cmd_watch)

    # Dashboard command
    dashboard_parser = subparsers.add_parser(
        "dashboard",
        help="Update the Dashboard.md file",
    )
    dashboard_parser.add_argument(
        "--vault",
        type=str,
        default="~/AI_Employee_Vault",
        help="Path to the Obsidian vault (default: ~/AI_Employee_Vault)",
    )
    dashboard_parser.set_defaults(func=cmd_dashboard)

    # Gmail watch command
    gmail_parser = subparsers.add_parser(
        "watch-gmail",
        help="Start the Gmail watcher",
    )
    gmail_parser.add_argument(
        "--vault",
        type=str,
        default="~/AI_Employee_Vault",
        help="Path to the Obsidian vault (default: ~/AI_Employee_Vault)",
    )
    gmail_parser.add_argument(
        "--credentials",
        type=str,
        help="Path to Gmail OAuth2 credentials.json",
    )
    gmail_parser.add_argument(
        "--interval",
        type=int,
        default=120,
        help="Poll interval in seconds (default: 120)",
    )
    gmail_parser.set_defaults(func=cmd_gmail_watch)

    # Init command
    init_parser = subparsers.add_parser(
        "init",
        help="Initialize the vault structure",
    )
    init_parser.add_argument(
        "--vault",
        type=str,
        default="~/AI_Employee_Vault",
        help="Path to create the Obsidian vault (default: ~/AI_Employee_Vault)",
    )
    init_parser.set_defaults(func=cmd_init)

    return parser


def main() -> int:
    """Main entry point for the CLI.

    Returns:
        Exit code
    """
    parser = create_parser()
    args = parser.parse_args()

    result: int = args.func(args)
    return result


if __name__ == "__main__":
    sys.exit(main())
