"""Dashboard State model - current system status displayed to user."""

from dataclasses import dataclass, field
from datetime import datetime

from ai_employee.models.activity_log import ActivityLogEntry


@dataclass
class DashboardState:
    """Current system status displayed in Dashboard.md.

    Sections:
    - Status: Watcher state, pending count, today's processed count
    - Recent Activity: Last 10 activity log entries as table
    - Warnings: Error alerts if threshold exceeded
    """

    last_updated: datetime
    watcher_status: str = "unknown"  # running, stopped, unknown
    pending_count: int = 0
    processed_today: int = 0
    recent_activity: list[ActivityLogEntry] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    error_count_hour: int = 0

    def to_markdown(self) -> str:
        """Generate Dashboard.md content from state."""
        lines = [
            "# AI Employee Dashboard",
            "",
            f"**Last Updated**: {self.last_updated.strftime('%Y-%m-%d %H:%M:%S')}",
            "",
            "## Status",
            "",
            f"- **Watcher**: {self.watcher_status}",
            f"- **Pending Items**: {self.pending_count}",
            f"- **Processed Today**: {self.processed_today}",
            "",
            "## Recent Activity",
            "",
            "| Time | Action | Item | Result |",
            "|------|--------|------|--------|",
        ]

        if self.recent_activity:
            for entry in self.recent_activity[:10]:
                time_str = entry.timestamp.strftime("%H:%M:%S")
                lines.append(
                    f"| {time_str} | {entry.action_type.value} | "
                    f"{entry.item_id} | {entry.outcome.value} |"
                )
        else:
            lines.append("| - | - | - | - |")

        lines.extend(["", "## Warnings", ""])

        if self.warnings:
            for warning in self.warnings:
                lines.append(f"- {warning}")
        else:
            lines.append("None")

        lines.extend(["", "---", "*Auto-generated by AI Employee*"])

        return "\n".join(lines)
